const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  openDirectoryDialog: () => ipcRenderer.invoke('dialog:openDirectory'),
  getProjects: () => ipcRenderer.invoke('config:getProjects'),
  saveProjects: (config) => ipcRenderer.invoke('config:saveProjects', config),
  getRecentSessions: (projectPath) => ipcRenderer.invoke('sessions:getRecent', projectPath),
  saveSessions: (projectPath, sessionIds) => ipcRenderer.invoke('sessions:save', projectPath, sessionIds),
  loadSessions: (projectPath) => ipcRenderer.invoke('sessions:load', projectPath),
  getSessionTitle: (projectPath, sessionId) => ipcRenderer.invoke('sessions:getTitle', projectPath, sessionId),
  readClaudeMd: (projectPath) => ipcRenderer.invoke('claudemd:read', projectPath),
  saveClaudeMd: (projectPath, content) => ipcRenderer.invoke('claudemd:save', projectPath, content),
  readDir: (dirPath) => ipcRenderer.invoke('fs:readDir', dirPath),
  readFile: (filePath) => ipcRenderer.invoke('fs:readFile', filePath),
  writeFile: (filePath, content) => ipcRenderer.invoke('fs:writeFile', filePath, content),
  gitStatus: (projectPath) => ipcRenderer.invoke('git:status', projectPath),
  gitBranch: (projectPath) => ipcRenderer.invoke('git:branch', projectPath),
  gitStageFile: (projectPath, filePath) => ipcRenderer.invoke('git:stageFile', projectPath, filePath),
  gitUnstageFile: (projectPath, filePath) => ipcRenderer.invoke('git:unstageFile', projectPath, filePath),
  gitStageAll: (projectPath) => ipcRenderer.invoke('git:stageAll', projectPath),
  gitUnstageAll: (projectPath) => ipcRenderer.invoke('git:unstageAll', projectPath),
  gitCommit: (projectPath, message, amend) => ipcRenderer.invoke('git:commit', projectPath, message, amend),
  gitPull: (projectPath) => ipcRenderer.invoke('git:pull', projectPath),
  gitPush: (projectPath) => ipcRenderer.invoke('git:push', projectPath),
  gitDiscardFile: (projectPath, filePath) => ipcRenderer.invoke('git:discardFile', projectPath, filePath),
  gitBranches: (projectPath) => ipcRenderer.invoke('git:branches', projectPath),
  gitCheckout: (projectPath, branch) => ipcRenderer.invoke('git:checkout', projectPath, branch),
  gitCreateBranch: (projectPath, branchName) => ipcRenderer.invoke('git:createBranch', projectPath, branchName),
  gitAheadBehind: (projectPath) => ipcRenderer.invoke('git:aheadBehind', projectPath),
  gitDiff: (projectPath, filePath, staged) => ipcRenderer.invoke('git:diff', projectPath, filePath, staged),
  gitLog: (projectPath, count) => ipcRenderer.invoke('git:log', projectPath, count),
  gitStashList: (projectPath) => ipcRenderer.invoke('git:stashList', projectPath),
  gitStashPush: (projectPath, message) => ipcRenderer.invoke('git:stashPush', projectPath, message),
  gitStashPop: (projectPath) => ipcRenderer.invoke('git:stashPop', projectPath),
  getLaunchConfigs: (projectPath) => ipcRenderer.invoke('launch:getConfigs', projectPath),
  getUsage: () => ipcRenderer.invoke('usage:getAll'),
  getVersion: () => ipcRenderer.invoke('app:getVersion'),
  onUpdateAvailable: (callback) => ipcRenderer.on('update:available', (_, info) => callback(info)),
  onUpdateDownloaded: (callback) => ipcRenderer.on('update:downloaded', (_, info) => callback(info)),
  onUpdateProgress: (callback) => ipcRenderer.on('update:progress', (_, info) => callback(info)),
  onUpdateError: (callback) => ipcRenderer.on('update:error', (_, info) => callback(info)),
  installUpdate: () => ipcRenderer.invoke('update:install')
});
