const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  openDirectoryDialog: () => ipcRenderer.invoke('dialog:openDirectory'),
  getProjects: () => ipcRenderer.invoke('config:getProjects'),
  saveProjects: (config) => ipcRenderer.invoke('config:saveProjects', config),
  popOutProject: (projectKey) => ipcRenderer.invoke('project:popOut', projectKey),
  popInProject: (projectKey) => ipcRenderer.invoke('project:popIn', projectKey),
  focusPopoutWindow: (projectKey) => ipcRenderer.invoke('project:focusPopoutWindow', projectKey),
  closePopoutWindow: (projectKey) => ipcRenderer.invoke('project:closePopoutWindow', projectKey),
  popoutSetTransfer: (projectKey, list) => ipcRenderer.invoke('popout:setTransfer', projectKey, list),
  popoutTakeTransfer: (projectKey) => ipcRenderer.invoke('popout:takeTransfer', projectKey),
  onConfigUpdated: (callback) => ipcRenderer.on('config:updated', (_, cfg) => callback(cfg)),
  getRecentSessions: (projectPath) => ipcRenderer.invoke('sessions:getRecent', projectPath),
  saveSessions: (projectPath, sessionIds) => ipcRenderer.invoke('sessions:save', projectPath, sessionIds),
  loadSessions: (projectPath) => ipcRenderer.invoke('sessions:load', projectPath),
  getSessionTitle: (projectPath, sessionId) => ipcRenderer.invoke('sessions:getTitle', projectPath, sessionId),
  readClaudeMd: (projectPath) => ipcRenderer.invoke('claudemd:read', projectPath),
  saveClaudeMd: (projectPath, content) => ipcRenderer.invoke('claudemd:save', projectPath, content),
  readDir: (dirPath) => ipcRenderer.invoke('fs:readDir', dirPath),
  searchFiles: (rootDir, query) => ipcRenderer.invoke('fs:searchFiles', rootDir, query),
  readFile: (filePath) => ipcRenderer.invoke('fs:readFile', filePath),
  writeFile: (filePath, content) => ipcRenderer.invoke('fs:writeFile', filePath, content),
  gitStatus: (projectPath) => ipcRenderer.invoke('git:status', projectPath),
  gitBranch: (projectPath) => ipcRenderer.invoke('git:branch', projectPath),
  gitStageFile: (projectPath, filePath) => ipcRenderer.invoke('git:stageFile', projectPath, filePath),
  gitUnstageFile: (projectPath, filePath) => ipcRenderer.invoke('git:unstageFile', projectPath, filePath),
  gitStageAll: (projectPath) => ipcRenderer.invoke('git:stageAll', projectPath),
  gitUnstageAll: (projectPath) => ipcRenderer.invoke('git:unstageAll', projectPath),
  gitCommit: (projectPath, message, amend) => ipcRenderer.invoke('git:commit', projectPath, message, amend),
  gitPull: (projectPath) => ipcRenderer.invoke('git:pull', projectPath),
  gitPush: (projectPath) => ipcRenderer.invoke('git:push', projectPath),
  gitDiscardFile: (projectPath, filePath) => ipcRenderer.invoke('git:discardFile', projectPath, filePath),
  gitBranches: (projectPath) => ipcRenderer.invoke('git:branches', projectPath),
  gitCheckout: (projectPath, branch) => ipcRenderer.invoke('git:checkout', projectPath, branch),
  gitCreateBranch: (projectPath, branchName) => ipcRenderer.invoke('git:createBranch', projectPath, branchName),
  gitAheadBehind: (projectPath) => ipcRenderer.invoke('git:aheadBehind', projectPath),
  gitDiff: (projectPath, filePath, staged) => ipcRenderer.invoke('git:diff', projectPath, filePath, staged),
  gitGraphLog: (projectPath, count) => ipcRenderer.invoke('git:graphLog', projectPath, count),
  gitCommitDetail: (projectPath, hash) => ipcRenderer.invoke('git:commitDetail', projectPath, hash),
  gitDiffCommit: (projectPath, hash, filePath) => ipcRenderer.invoke('git:diffCommit', projectPath, hash, filePath),
  gitDiffStat: (projectPath, staged) => ipcRenderer.invoke('git:diffStat', projectPath, staged),
  gitStashList: (projectPath) => ipcRenderer.invoke('git:stashList', projectPath),
  gitStashPush: (projectPath, message) => ipcRenderer.invoke('git:stashPush', projectPath, message),
  gitStashPop: (projectPath) => ipcRenderer.invoke('git:stashPop', projectPath),
  getLaunchConfigs: (projectPath) => ipcRenderer.invoke('launch:getConfigs', projectPath),
  saveLaunchConfigs: (projectPath, configs) => ipcRenderer.invoke('launch:saveConfigs', projectPath, configs),
  saveEnvProfiles: (projectPath, profiles) => ipcRenderer.invoke('launch:saveEnvProfiles', projectPath, profiles),
  scanCsproj: (dirPath) => ipcRenderer.invoke('launch:scanCsproj', dirPath),
  browseFile: (filters) => ipcRenderer.invoke('launch:browseFile', filters),
  readEnvFile: (filePath) => ipcRenderer.invoke('launch:readEnvFile', filePath),
  saveRecentLaunches: (projectPath, recent) => ipcRenderer.invoke('launch:saveRecentLaunches', projectPath, recent),
  getUsage: () => ipcRenderer.invoke('usage:getAll'),
  getUsageCosts: (filter) => ipcRenderer.invoke('usage:getCosts', filter),
  searchSessions: (query, limit) => ipcRenderer.invoke('sessions:search', query, limit),
  searchHistory: (query, limit) => ipcRenderer.invoke('history:search', query, limit),
  listSnippets: () => ipcRenderer.invoke('snippets:list'),
  saveSnippet: (snippet) => ipcRenderer.invoke('snippets:save', snippet),
  deleteSnippet: (id) => ipcRenderer.invoke('snippets:delete', id),
  getPlanLimits: (force) => ipcRenderer.invoke('usage:getPlanLimits', force),
  detectThresholdCrossings: (prev, next) => ipcRenderer.invoke('usage:detectThresholdCrossings', prev, next),
  getSessionContextTokens: (projectKey, sessionId) => ipcRenderer.invoke('session:contextTokens', projectKey, sessionId),
  getModelContextLimit: (model) => ipcRenderer.invoke('session:modelContextLimit', model),
  showSystemNotification: (opts) => ipcRenderer.invoke('notify:show', opts),
  getVersion: () => ipcRenderer.invoke('app:getVersion'),
  onUpdateAvailable: (callback) => ipcRenderer.on('update:available', (_, info) => callback(info)),
  onUpdateDownloaded: (callback) => ipcRenderer.on('update:downloaded', (_, info) => callback(info)),
  onUpdateProgress: (callback) => ipcRenderer.on('update:progress', (_, info) => callback(info)),
  onUpdateError: (callback) => ipcRenderer.on('update:error', (_, info) => callback(info)),
  installUpdate: () => ipcRenderer.invoke('update:install'),
  clipboardReadText: () => ipcRenderer.invoke('clipboard:readText'),
  clipboardWriteText: (text) => ipcRenderer.invoke('clipboard:writeText', text),
  setTitleBarOverlay: (colors) => ipcRenderer.invoke('theme:setTitleBarOverlay', colors),
  getOsDark: () => ipcRenderer.invoke('theme:getOsDark'),
  getClaudeConfigPath: () => ipcRenderer.invoke('claude:getConfigPath'),
  onOsThemeChanged: (callback) => ipcRenderer.on('theme:osChanged', (_, isDark) => callback(isDark)),
  getStartWithOS: () => ipcRenderer.invoke('app:getStartWithOS'),
  setStartWithOS: (enabled) => ipcRenderer.invoke('app:setStartWithOS', enabled),
  getPtyPort: () => ipcRenderer.invoke('pty:getPort'),
  flashFrame: () => ipcRenderer.invoke('window:flashFrame'),
  stopFlashFrame: () => ipcRenderer.invoke('window:stopFlashFrame'),
  getHookServerPort: () => ipcRenderer.invoke('hooks:getPort'),
  onHookEvent: (callback) => ipcRenderer.on('hook:event', (_, event) => callback(event)),
  configureHooks: () => ipcRenderer.invoke('hooks:configure'),
  disconnectHooks: () => ipcRenderer.invoke('hooks:disconnect'),
  isHooksConfigured: () => ipcRenderer.invoke('hooks:isConfigured'),
  openExternal: (url) => ipcRenderer.invoke('shell:openExternal', url),
  showItemInFolder: (fullPath) => ipcRenderer.invoke('shell:showItemInFolder', fullPath),
  openPath: (fullPath) => ipcRenderer.invoke('shell:openPath', fullPath),

  // Automations
  getAutomations: () => ipcRenderer.invoke('automations:getAll'),
  getAutomationsForProject: (projectPath) => ipcRenderer.invoke('automations:getForProject', projectPath),
  createAutomation: (config) => ipcRenderer.invoke('automations:create', config),
  updateAutomation: (automationId, updates) => ipcRenderer.invoke('automations:update', automationId, updates),
  deleteAutomation: (automationId) => ipcRenderer.invoke('automations:delete', automationId),
  updateAgent: (automationId, agentId, updates) => ipcRenderer.invoke('automations:updateAgent', automationId, agentId, updates),
  addAgent: (automationId, agentConfig) => ipcRenderer.invoke('automations:addAgent', automationId, agentConfig),
  removeAgent: (automationId, agentId) => ipcRenderer.invoke('automations:removeAgent', automationId, agentId),
  toggleAutomation: (automationId) => ipcRenderer.invoke('automations:toggle', automationId),
  toggleAgent: (automationId, agentId) => ipcRenderer.invoke('automations:toggleAgent', automationId, agentId),
  setAllAutomationsEnabled: (projectPath, enabled) => ipcRenderer.invoke('automations:setAllEnabled', projectPath, enabled),
  toggleAutomationsGlobal: () => ipcRenderer.invoke('automations:toggleGlobal'),
  runAgentNow: (automationId, agentId) => ipcRenderer.invoke('automations:runAgentNow', automationId, agentId),
  runAutomationNow: (automationId) => ipcRenderer.invoke('automations:runAutomationNow', automationId),
  getAgentHistory: (automationId, agentId, count) => ipcRenderer.invoke('automations:getAgentHistory', automationId, agentId, count),
  getAgentRunDetail: (automationId, agentId, startedAt) => ipcRenderer.invoke('automations:getAgentRunDetail', automationId, agentId, startedAt),
  getAgentLiveOutput: (automationId, agentId) => ipcRenderer.invoke('automations:getAgentLiveOutput', automationId, agentId),
  setupAgentClone: (automationId, agentId) => ipcRenderer.invoke('automations:setupAgentClone', automationId, agentId),
  getCloneStatus: (automationId) => ipcRenderer.invoke('automations:getCloneStatus', automationId),
  validateDependencies: (agents) => ipcRenderer.invoke('automations:validateDependencies', agents),
  exportAutomations: (projectPath) => ipcRenderer.invoke('automations:export', projectPath),
  exportAutomation: (automationId) => ipcRenderer.invoke('automations:exportOne', automationId),
  previewImport: () => ipcRenderer.invoke('automations:previewImport'),
  importAutomations: (projectPath, filePath) => ipcRenderer.invoke('automations:import', projectPath, filePath),
  deleteAllAutomations: (projectPath) => ipcRenderer.invoke('automations:deleteAllForProject', projectPath),
  getAutomationSettings: () => ipcRenderer.invoke('automations:getSettings'),
  updateAutomationSettings: (settings) => ipcRenderer.invoke('automations:updateSettings', settings),
  onAgentStarted: (callback) => ipcRenderer.on('automations:agent-started', (_, data) => callback(data)),
  onAgentCompleted: (callback) => ipcRenderer.on('automations:agent-completed', (_, data) => callback(data)),
  onAgentOutput: (callback) => ipcRenderer.on('automations:agent-output', (_, data) => callback(data)),
  onCloneProgress: (callback) => ipcRenderer.on('automations:clone-progress', (_, data) => callback(data)),
  runManager: (automationId) => ipcRenderer.invoke('automations:runManager', automationId),
  dismissManager: (automationId) => ipcRenderer.invoke('automations:dismissManager', automationId),
  getManagerStatus: (automationId) => ipcRenderer.invoke('automations:getManagerStatus', automationId),
  getManagerHistory: (automationId, count) => ipcRenderer.invoke('automations:getManagerHistory', automationId, count),
  setupManagerClone: (automationId) => ipcRenderer.invoke('automations:setupManagerClone', automationId),
  getManagerLiveOutput: (automationId) => ipcRenderer.invoke('automations:getManagerLiveOutput', automationId),
  onManagerOutput: (callback) => ipcRenderer.on('automations:manager-output', (_, data) => callback(data)),
  onManagerStarted: (callback) => ipcRenderer.on('automations:manager-started', (_, data) => callback(data)),
  onManagerCompleted: (callback) => ipcRenderer.on('automations:manager-completed', (_, data) => callback(data)),
  onFocusManager: (callback) => ipcRenderer.on('automations:focus-manager', (_, data) => callback(data)),

  // Headless runs
  headlessRun: (projectPath, prompt) => ipcRenderer.invoke('headless:run', projectPath, prompt),
  headlessList: (projectPath) => ipcRenderer.invoke('headless:list', projectPath),
  headlessGet: (projectPath, runId) => ipcRenderer.invoke('headless:get', projectPath, runId),
  headlessCancel: (runId) => ipcRenderer.invoke('headless:cancel', runId),
  headlessDelete: (projectPath, runId) => ipcRenderer.invoke('headless:delete', projectPath, runId),
  onHeadlessStarted: (callback) => ipcRenderer.on('headless:started', (_, data) => callback(data)),
  onHeadlessOutput: (callback) => ipcRenderer.on('headless:output', (_, data) => callback(data)),
  onHeadlessCompleted: (callback) => ipcRenderer.on('headless:completed', (_, data) => callback(data)),
  onHeadlessFocusRun: (callback) => ipcRenderer.on('headless:focus-run', (_, data) => callback(data)),
  onPowerResume: (callback) => ipcRenderer.on('power:resume', () => callback()),

  // Endpoint presets
  endpointList: () => ipcRenderer.invoke('endpoint:list'),
  endpointGet: (id) => ipcRenderer.invoke('endpoint:get', id),
  endpointSave: (preset) => ipcRenderer.invoke('endpoint:save', preset),
  endpointDelete: (id) => ipcRenderer.invoke('endpoint:delete', id),
  endpointGetEnv: (id, modelOverride) => ipcRenderer.invoke('endpoint:getEnv', id, modelOverride),
  endpointFetchModels: (args) => ipcRenderer.invoke('endpoint:fetchModels', args),
  onEndpointsUpdated: (callback) => ipcRenderer.on('endpoints:updated', () => callback()),

  paletteRank: (items, query) => ipcRenderer.invoke('palette:rank', items, query)
});
