const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  openDirectoryDialog: () => ipcRenderer.invoke('dialog:openDirectory'),
  getProjects: () => ipcRenderer.invoke('config:getProjects'),
  saveProjects: (config) => ipcRenderer.invoke('config:saveProjects', config),
  getRecentSessions: (projectPath) => ipcRenderer.invoke('sessions:getRecent', projectPath),
  saveSessions: (projectPath, sessionIds) => ipcRenderer.invoke('sessions:save', projectPath, sessionIds),
  loadSessions: (projectPath) => ipcRenderer.invoke('sessions:load', projectPath),
  getSessionTitle: (projectPath, sessionId) => ipcRenderer.invoke('sessions:getTitle', projectPath, sessionId),
  readClaudeMd: (projectPath) => ipcRenderer.invoke('claudemd:read', projectPath),
  saveClaudeMd: (projectPath, content) => ipcRenderer.invoke('claudemd:save', projectPath, content),
  readDir: (dirPath) => ipcRenderer.invoke('fs:readDir', dirPath),
  searchFiles: (rootDir, query) => ipcRenderer.invoke('fs:searchFiles', rootDir, query),
  readFile: (filePath) => ipcRenderer.invoke('fs:readFile', filePath),
  writeFile: (filePath, content) => ipcRenderer.invoke('fs:writeFile', filePath, content),
  gitStatus: (projectPath) => ipcRenderer.invoke('git:status', projectPath),
  gitBranch: (projectPath) => ipcRenderer.invoke('git:branch', projectPath),
  gitStageFile: (projectPath, filePath) => ipcRenderer.invoke('git:stageFile', projectPath, filePath),
  gitUnstageFile: (projectPath, filePath) => ipcRenderer.invoke('git:unstageFile', projectPath, filePath),
  gitStageAll: (projectPath) => ipcRenderer.invoke('git:stageAll', projectPath),
  gitUnstageAll: (projectPath) => ipcRenderer.invoke('git:unstageAll', projectPath),
  gitCommit: (projectPath, message, amend) => ipcRenderer.invoke('git:commit', projectPath, message, amend),
  gitPull: (projectPath) => ipcRenderer.invoke('git:pull', projectPath),
  gitPush: (projectPath) => ipcRenderer.invoke('git:push', projectPath),
  gitDiscardFile: (projectPath, filePath) => ipcRenderer.invoke('git:discardFile', projectPath, filePath),
  gitBranches: (projectPath) => ipcRenderer.invoke('git:branches', projectPath),
  gitCheckout: (projectPath, branch) => ipcRenderer.invoke('git:checkout', projectPath, branch),
  gitCreateBranch: (projectPath, branchName) => ipcRenderer.invoke('git:createBranch', projectPath, branchName),
  gitAheadBehind: (projectPath) => ipcRenderer.invoke('git:aheadBehind', projectPath),
  gitDiff: (projectPath, filePath, staged) => ipcRenderer.invoke('git:diff', projectPath, filePath, staged),
  gitGraphLog: (projectPath, count) => ipcRenderer.invoke('git:graphLog', projectPath, count),
  gitCommitDetail: (projectPath, hash) => ipcRenderer.invoke('git:commitDetail', projectPath, hash),
  gitDiffCommit: (projectPath, hash, filePath) => ipcRenderer.invoke('git:diffCommit', projectPath, hash, filePath),
  gitDiffStat: (projectPath, staged) => ipcRenderer.invoke('git:diffStat', projectPath, staged),
  gitStashList: (projectPath) => ipcRenderer.invoke('git:stashList', projectPath),
  gitStashPush: (projectPath, message) => ipcRenderer.invoke('git:stashPush', projectPath, message),
  gitStashPop: (projectPath) => ipcRenderer.invoke('git:stashPop', projectPath),
  getLaunchConfigs: (projectPath) => ipcRenderer.invoke('launch:getConfigs', projectPath),
  saveLaunchConfigs: (projectPath, configs) => ipcRenderer.invoke('launch:saveConfigs', projectPath, configs),
  saveEnvProfiles: (projectPath, profiles) => ipcRenderer.invoke('launch:saveEnvProfiles', projectPath, profiles),
  scanCsproj: (dirPath) => ipcRenderer.invoke('launch:scanCsproj', dirPath),
  browseFile: (filters) => ipcRenderer.invoke('launch:browseFile', filters),
  readEnvFile: (filePath) => ipcRenderer.invoke('launch:readEnvFile', filePath),
  saveRecentLaunches: (projectPath, recent) => ipcRenderer.invoke('launch:saveRecentLaunches', projectPath, recent),
  getUsage: () => ipcRenderer.invoke('usage:getAll'),
  getVersion: () => ipcRenderer.invoke('app:getVersion'),
  onUpdateAvailable: (callback) => ipcRenderer.on('update:available', (_, info) => callback(info)),
  onUpdateDownloaded: (callback) => ipcRenderer.on('update:downloaded', (_, info) => callback(info)),
  onUpdateProgress: (callback) => ipcRenderer.on('update:progress', (_, info) => callback(info)),
  onUpdateError: (callback) => ipcRenderer.on('update:error', (_, info) => callback(info)),
  installUpdate: () => ipcRenderer.invoke('update:install'),
  clipboardReadText: () => ipcRenderer.invoke('clipboard:readText'),
  clipboardWriteText: (text) => ipcRenderer.invoke('clipboard:writeText', text),
  setTitleBarOverlay: (colors) => ipcRenderer.invoke('theme:setTitleBarOverlay', colors),
  getOsDark: () => ipcRenderer.invoke('theme:getOsDark'),
  getClaudeConfigPath: () => ipcRenderer.invoke('claude:getConfigPath'),
  onOsThemeChanged: (callback) => ipcRenderer.on('theme:osChanged', (_, isDark) => callback(isDark)),
  getStartWithOS: () => ipcRenderer.invoke('app:getStartWithOS'),
  setStartWithOS: (enabled) => ipcRenderer.invoke('app:setStartWithOS', enabled),
  getPtyPort: () => ipcRenderer.invoke('pty:getPort'),
  flashFrame: () => ipcRenderer.invoke('window:flashFrame'),
  getHookServerPort: () => ipcRenderer.invoke('hooks:getPort'),
  onHookEvent: (callback) => ipcRenderer.on('hook:event', (_, event) => callback(event)),
  openExternal: (url) => ipcRenderer.invoke('shell:openExternal', url),
  showItemInFolder: (fullPath) => ipcRenderer.invoke('shell:showItemInFolder', fullPath),
  openPath: (fullPath) => ipcRenderer.invoke('shell:openPath', fullPath),

  // Loops
  getLoops: () => ipcRenderer.invoke('loops:getAll'),
  getLoopsForProject: (projectPath) => ipcRenderer.invoke('loops:getForProject', projectPath),
  createLoop: (config) => ipcRenderer.invoke('loops:create', config),
  updateLoop: (loopId, updates) => ipcRenderer.invoke('loops:update', loopId, updates),
  deleteLoop: (loopId) => ipcRenderer.invoke('loops:delete', loopId),
  toggleLoop: (loopId) => ipcRenderer.invoke('loops:toggle', loopId),
  toggleLoopsGlobal: () => ipcRenderer.invoke('loops:toggleGlobal'),
  runLoopNow: (loopId) => ipcRenderer.invoke('loops:runNow', loopId),
  getLoopHistory: (loopId, count) => ipcRenderer.invoke('loops:getHistory', loopId, count),
  getLoopRunDetail: (loopId, startedAt) => ipcRenderer.invoke('loops:getRunDetail', loopId, startedAt),
  getLoopLiveOutput: (loopId) => ipcRenderer.invoke('loops:getLiveOutput', loopId),
  exportLoops: (projectPath) => ipcRenderer.invoke('loops:export', projectPath),
  exportLoop: (loopId) => ipcRenderer.invoke('loops:exportOne', loopId),
  importLoops: (projectPath) => ipcRenderer.invoke('loops:import', projectPath),
  onLoopRunStarted: (callback) => ipcRenderer.on('loops:run-started', (_, data) => callback(data)),
  onLoopRunCompleted: (callback) => ipcRenderer.on('loops:run-completed', (_, data) => callback(data)),
  onLoopOutput: (callback) => ipcRenderer.on('loops:output', (_, data) => callback(data)),

  // Automations
  getAutomations: () => ipcRenderer.invoke('automations:getAll'),
  getAutomationsForProject: (projectPath) => ipcRenderer.invoke('automations:getForProject', projectPath),
  createAutomation: (config) => ipcRenderer.invoke('automations:create', config),
  updateAutomation: (automationId, updates) => ipcRenderer.invoke('automations:update', automationId, updates),
  deleteAutomation: (automationId) => ipcRenderer.invoke('automations:delete', automationId),
  updateAgent: (automationId, agentId, updates) => ipcRenderer.invoke('automations:updateAgent', automationId, agentId, updates),
  addAgent: (automationId, agentConfig) => ipcRenderer.invoke('automations:addAgent', automationId, agentConfig),
  removeAgent: (automationId, agentId) => ipcRenderer.invoke('automations:removeAgent', automationId, agentId),
  toggleAutomation: (automationId) => ipcRenderer.invoke('automations:toggle', automationId),
  toggleAgent: (automationId, agentId) => ipcRenderer.invoke('automations:toggleAgent', automationId, agentId),
  toggleAutomationsGlobal: () => ipcRenderer.invoke('automations:toggleGlobal'),
  runAgentNow: (automationId, agentId) => ipcRenderer.invoke('automations:runAgentNow', automationId, agentId),
  runAutomationNow: (automationId) => ipcRenderer.invoke('automations:runAutomationNow', automationId),
  getAgentHistory: (automationId, agentId, count) => ipcRenderer.invoke('automations:getAgentHistory', automationId, agentId, count),
  getAgentRunDetail: (automationId, agentId, startedAt) => ipcRenderer.invoke('automations:getAgentRunDetail', automationId, agentId, startedAt),
  getAgentLiveOutput: (automationId, agentId) => ipcRenderer.invoke('automations:getAgentLiveOutput', automationId, agentId),
  setupAgentClone: (automationId, agentId) => ipcRenderer.invoke('automations:setupAgentClone', automationId, agentId),
  getCloneStatus: (automationId) => ipcRenderer.invoke('automations:getCloneStatus', automationId),
  validateDependencies: (agents) => ipcRenderer.invoke('automations:validateDependencies', agents),
  exportAutomations: (projectPath) => ipcRenderer.invoke('automations:export', projectPath),
  exportAutomation: (automationId) => ipcRenderer.invoke('automations:exportOne', automationId),
  importAutomations: (projectPath) => ipcRenderer.invoke('automations:import', projectPath),
  getAutomationSettings: () => ipcRenderer.invoke('automations:getSettings'),
  updateAutomationSettings: (settings) => ipcRenderer.invoke('automations:updateSettings', settings),
  onAgentStarted: (callback) => ipcRenderer.on('automations:agent-started', (_, data) => callback(data)),
  onAgentCompleted: (callback) => ipcRenderer.on('automations:agent-completed', (_, data) => callback(data)),
  onAgentOutput: (callback) => ipcRenderer.on('automations:agent-output', (_, data) => callback(data)),
  onCloneProgress: (callback) => ipcRenderer.on('automations:clone-progress', (_, data) => callback(data))
});
